### ISSUE TITLE
Lack of Releases

### ISSUE THREAD

**Issue by clay53** [idiidk/kahoot-api#11]
There hasn't been a release on GitHub since 0.2.1 Alpha. I would like to use the client-side version of this package but there isn't a working one I can find.

**Comment by idiidk** [comment]
I'm updating this package as I work on kahoot-tools. So when I need a feature for kahoot-tools I add it to this package. It should work in its current state tho, only some features aren't implemented. They should be easy to add. 

I won't be updating it until I need it. If you need some specific feature I might be able to take a look tho.
