### ISSUE TITLE
The requested module does not provide an export named 'Session'

### ISSUE THREAD

**Issue by 4424dev** [idiidk/kahoot-api#12]
Hey, hope all is going well.

I am trying to use your API to make my own tool, like omegaboot.

I use the default code on NPM, with a few modifications to the import path, but get this error:

`The requested module './node_modules/@omegaboot/kahoot-api/dist/index.js' does not provide an export named 'Session'`

What am I doing wrong? I have NEVER used JS import before, sorry.

Thanks!

**Comment by idiidk** [comment]
Don't use @omegaboot/kahoot-api. That is a custom package for omegaboot only. Use the normal kahoot-api.
