### ISSUE TITLE
Quiz?

### ISSUE THREAD

**Issue by JeroenoBoy** [idiidk/kahoot-api#13]
Can you please post some examples on how to make the bots answer questions? i can't wrap my head around it

**Comment by idiidk** [comment]
You

**Comment by idiidk** [comment]
yes I can do it

**Comment by idiidk** [comment]
You need to select the player group by clicking on it from the bottom menu. Then click on any option in the answer boz

**Comment by JeroenoBoy** [comment]
THis is kahoot-api not omegabot

**Comment by idiidk** [comment]
Call .answer(choice) on any player adapter where choice is a number between 0 and 3. 0 being the first option, 3 the last.
