### ISSUE TITLE
Stacked promises are messy

### ISSUE THREAD

**Issue by yvelnox** [idiidk/kahoot-api#9]
I personally think nested promises are extremely messy. I think if the code was changed to use call backs it would be a lot easier for someone using this package (and yes I do know changing from promises to call backs takes a lot of work).

**Comment by idiidk** [comment]
Wouldn't callbacks inside of callbacks cause the same issues? At least with promises you can use async await. Could you provide me with an example of where callbacks would be more stylistic in you opinion, then I can truly consider it. Thank you!

**Comment by idiidk** [comment]
Closed due to inactivity
